const products = [
  {
    id: 1,
    name: 'Худі "САПСАН 1.0"',
    price: 1890,
    category: 'clothes',
    images: [
      './img/hoodie_1_1.jpg',
      './img/hoodie_1_2.jpg',
      './img/hoodie_1_3.jpg',
    ],
    inStock: true,
    sizes: { S: true, M: true, L: true, XL: true, XXL: false },
  },
  {
    id: 2,
    name: 'Футболка "САПСАН"',
    price: 790,
    category: 'clothes',
    images: ['./img/t-short_1_1.jpg', './img/t-short_1_2.jpg'],
    inStock: true,
    sizes: { S: true, M: true, L: true, XL: true, XXL: true },
  },
  {
    id: 3,
    name: 'Кепка "САПСАН"',
    price: 490,
    category: 'clothes',
    images: ['./img/cap_1_2.jpg', './img/cap_1_1.jpg'],
    inStock: false,
    sizes: { S: false, M: false, L: false, XL: false, XXL: false },
  },
  {
    id: 4,
    name: 'Худі "САПСАН 2.0"',
    price: 1790,
    category: 'clothes',
    images: ['./img/hoodie_2_1.jpg', './img/hoodie_2_2.jpg'],
    inStock: true,
    sizes: { S: false, M: true, L: true, XL: true, XXL: true },
  },
  {
    id: 5,
    name: 'Футболка "САПСАН"',
    price: 690,
    category: 'clothes',
    images: ['./img/t-short_2_1.jpg', './img/t-short_2_2.jpg'],
    inStock: true,
    sizes: { S: true, M: true, L: false, XL: true, XXL: false },
  },
  {
    id: 6,
    name: 'Кепка "САПСАН"',
    price: 450,
    category: 'clothes',
    images: ['./img/cap_2_1.jpg', './img/cap_2_2.jpg'],
    inStock: true,
    sizes: { S: true, M: true, L: true, XL: true, XXL: true },
  },
  {
    id: 7,
    name: 'Блокнот батальйону',
    price: 290,
    category: 'accessories',
    images: ['./img/note_1_1.jpg', './img/note_1_2.jpg'],
    inStock: true,
  },

  {
    id: 8,
    name: 'Худі "САПСАН 3.0"',
    price: 1790,
    category: 'clothes',
    images: ['./img/hoodie_3_1.jpg', './img/hoodie_3_2.jpg'],
    inStock: true,
    sizes: { S: false, M: true, L: true, XL: true, XXL: true },
  },
  {
    id: 9,
    name: 'Ручка "САПСАН"',
    price: 89,
    category: 'stationery',
    images: ['./img/pen_1_1.jpg'],
    inStock: true,
  },
  {
    id: 10,
    name: 'Прапор батальону',
    price: 120,
    category: 'symbolism',
    images: ['./img/prapor_1_1.jpg'],
    inStock: true,
  },
  {
    id: 11,
    name: 'Набір стікерів',
    price: 149,
    category: 'stationery',
    images: ['./img/stikers_1.jpg'],
    inStock: true,
  },
  {
    id: 12,
    name: 'Брелок "САПСАН"',
    price: 99,
    category: 'accessories',
    images: ['./img/brelok_1_1.jpg'],
    inStock: true,
  },
  {
    id: 13,
    name: 'Термопляшка "САПСАН"',
    price: 79,
    category: 'accessories',
    images: ['./img/termo_buttle.jpg'],
    inStock: true,
  },
  {
    id: 14,
    name: 'Термокелих "САПСАН"',
    price: 79,
    category: 'accessories',
    images: ['./img/termo_cup_1_1.jpg', './img/termo_cup_1_2.jpg'],
    inStock: true,
  },
  {
    id: 15,
    name: 'Шеврон батальону',
    price: 120,
    category: 'symbolism',
    images: [''],
    inStock: true,
  },
  {
    id: 16,
    name: 'Шеврон батальону ПВХ',
    price: 120,
    category: 'symbolism',
    images: [''],
    inStock: true,
  },
  {
    id: 17,
    name: 'Шеврон батальону польовий',
    price: 120,
    category: 'symbolism',
    images: [''],
    inStock: true,
  },
]
